---
title: "Hernia"
description: |

  Hernias are characterized by protrusion of an organ or tissue through its surrounding cavity and often requires surgery, especially inguinal hernia repair in men is one of the most frequently performed operations.
date: 2022-08-24
output:
  distill::distill_article:
    self_contained: false
  theme: tidy_color_test.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The genetic epidemiology group at SSI performed genome-wide association study (GWAS) scans on 65,492 cases of inguinal, diaphragmatic, umbilical, femoral and ventral hernia and two combined groups against controls without a history of any hernia in the UK Biobank data.

The initial findings for inguinal hernia were followed up in 23,803 additional cases in study groups from Finland, Estonia and Denmark.

[Read this article in Danish.](https://www.ssi.dk/aktuelt/nyheder/2022/statens-serum-institut-finder-sammenhaeng-mellem-brok-og-vores-gener)

## Genetic variants relevant for multiple forms of hernia
In total, 81 genetic loci showed association with one or more of the analyzed hernia groups, many genetic variants were observed in more than one GWAS. Further testing showed that 26 loci were associated with more than one hernia type, suggesting substantial overlap between the underlying genetic mechanisms.

“This was the reason why we had decided to analyze the groups of all hernia cases and all hernia cases excluding individuals with only diaphragmatic hernia in the beginning. What we saw was that more than 40% of the loci identified in the UK Biobank scans had the lowest p-value in one of the combined groups”, says senior researcher Frank Geller, corresponding author of the study.

Additional pathway analyses identified several genes with a strong link to collagen and/or elastin close to associated genetic variants. Collagen and elastin are main components of the skin, pointing to an increased vulnerability in carriers of the risk variants.

Genetic correlation between diaphragmatic hernia and depression
Another interesting aspect of the study were the observed genetic correlations. Comparing the GWAS scans for the five forms of hernia with 245 GWAS scans for a wide spectrum of traits and diseases, especially diaphragmatic hernia showed a link to several anthropometric, cognitive, reproductive, smoking and psychiatric traits.

Frank Geller continues:

“In connection with the iPSYCH project, we took a closer look at six psychiatric disorders and found significant correlation for major depressive disorder with diaphragmatic (rg = 0.23, 95%-CI: 0.10-0.35) and ventral hernia (rg = 0.45, 95%-CI: 0.19-0.71). Mendelian randomization with major depressive disorder as instrumental variable showed a potential causal effect of major depressive disorder on diaphragmatic hernia and to a lesser extent on ventral hernia.”

Bjarke Feenstra, group leader of the genetic epidemiology group at SSI, puts the findings into perspective:

“This study is basic research, so we cannot provide immediate action items for patients. Nevertheless, the many identified genetic variants with moderate effect jointly point to an essential role of connective tissue morphology in the etiology of herniation, which can be valuable for subsequent research on prevention or surgical repair and aftercare of hernias.”

The article Fadista et al. [“Comprehensive genome-wide association study of different forms of hernia identifies more than 80 associated loci”](https://www.nature.com/articles/s41467-022-30921-4) was published in Nature Communications on June 9th 2022.

